import Head from 'next/head';
import Footer from '../components/Footer';
import Header from '../components/Header';
import CatalogPreview from '../components/homepage/CatalogPreview';
import ContentBanner from '../components/homepage/ContentBanner';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Monochrome Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      <main className="content">
        <header className="content-banner-main d-block d-lg-none">
          <ContentBanner></ContentBanner>
        </header>

        <section className="content-main">
          <CatalogPreview></CatalogPreview>
        </section>
      </main>

      <footer>
        <Footer></Footer>
      </footer>
    </div>
  );
}
