import Head from 'next/head';
import Footer from '../components/product-page/Footer';
import ProductPageHeader from '../components/product-page/ProductPageHeader';
import CatalogPreviews from '../components/product-page/homepage/CatalogPreview';
import ContentProduct from '../components/product-page/homepage/ContentProduct';


export default function ProductPage() {
  return (
    <div>
      <Head>
        <title>Product Page Description</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/images/favicon/monochrome-android-chrome.png"/>
      </Head>

      <ProductPageHeader></ProductPageHeader>

      <main className="content container">
        <ContentProduct></ContentProduct>

        <CatalogPreviews></CatalogPreviews>
      </main>

      <footer>
        <Footer></Footer>
      </footer>
    </div>
  );
}
